import {
  IoAddOutline,
  IoChevronForwardOutline,
  IoChevronBackOutline,
  IoRemoveOutline,
} from "react-icons/io5";
import { SlLocationPin } from "react-icons/sl";
import { LuPhone } from "react-icons/lu";
import { useEffect, useState } from "react";
import ExpandedItemsButton from "../Buttons/ExpandedItemsButton";
import { getAPI } from "@/Functions/apiFunction";

const StewardshipLeft = ({ stewardshipData, onSelectData, totalRecords, onNextPre }) => {
  // State hooks to manage expanded, selected items and the number of records to display
  const [expandedId, setExpandedId] = useState(null);
  const [selectedId, setSelectedId] = useState(null);
  const [displayedCount, setDisplayedCount] = useState(10);
  const [getDataMKID, setGetDataMKID] = useState([]);

  const data = [
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000016673393",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "EFX",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "EFX-100828668",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 95.56,
      "MATCH_SOURCE_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828668,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO6 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO6 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828668,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828668\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO6 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_REGION\": \"GREATER MANCHESTER\",\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000016673394",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "EFX",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "EFX-100828669",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 95.56,
      "MATCH_SOURCE_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828669,\n  \"EFX_LEGAL_NAME\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO7 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828669,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828669\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO7 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"551111\",\n  \"EFX_SECNAICS2\": \"551100\",\n  \"EFX_SECNAICSDESC1\": \"Offices of Bank Holding Companies\",\n  \"EFX_SECNAICSDESC2\": \"Management of Companies and Enterprises\",\n  \"EFX_SECSIC1\": \"6719\",\n  \"EFX_SECSIC2\": \"6722\",\n  \"EFX_SECSICDESC1\": \"OFFICES OF HOLDING COMPANIES, NEC\",\n  \"EFX_SECSICDESC2\": \"MANAGEMENT INVESTMENT OFFICES, OPEN-END\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000008656308",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "CS",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "CS-GB003/0/09019528",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 69.72,
      "MATCH_SOURCE_DATA": "{\n  \"ADDRESS1\": \"EVERSHEDS HOUSE\",\n  \"ADDRESS2\": \"70 GREAT BRIDGEWATER STREET\",\n  \"ADDRESS3\": \"MANCHESTER\",\n  \"COUNTRY\": \"UK\",\n  \"CS_COMPANY_ID\": \"UK09367077\",\n  \"DATE_OF_CHANGE\": \"2018-05-16\",\n  \"NAME\": \"SUNE GREEN HOLDCO10 LIMITED\",\n  \"OFFICE_TYPE\": \"1\",\n  \"ORG_NUMBER\": \"09019528\",\n  \"REG_NUMBER\": \"09019528\",\n  \"REG_TYPE\": 0,\n  \"STATUS\": \"2\",\n  \"XML_ID\": \"GB003/0/09019528\",\n  \"ZIP\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000008656306",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "CS",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "CS-GB003/0/09019526",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 69.72,
      "MATCH_SOURCE_DATA": "{\n  \"ADDRESS1\": \"EVERSHEDS HOUSE\",\n  \"ADDRESS2\": \"70 GREAT BRIDGEWATER STREET\",\n  \"ADDRESS3\": \"MANCHESTER\",\n  \"COUNTRY\": \"UK\",\n  \"CS_COMPANY_ID\": \"UK09367075\",\n  \"DATE_OF_CHANGE\": \"2018-05-16\",\n  \"NAME\": \"SUNE GREEN HOLDCO12 LIMITED\",\n  \"OFFICE_TYPE\": \"1\",\n  \"ORG_NUMBER\": \"09019526\",\n  \"REG_NUMBER\": \"09019526\",\n  \"REG_TYPE\": 0,\n  \"STATUS\": \"2\",\n  \"XML_ID\": \"GB003/0/09019526\",\n  \"ZIP\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000016673391",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "EFX",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "EFX-100828666",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 95.56,
      "MATCH_SOURCE_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828666,\n  \"EFX_LEGAL_NAME\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO4 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828666,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828666\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO4 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"551111\",\n  \"EFX_SECNAICS2\": \"551100\",\n  \"EFX_SECNAICSDESC1\": \"Offices of Bank Holding Companies\",\n  \"EFX_SECNAICSDESC2\": \"Management of Companies and Enterprises\",\n  \"EFX_SECSIC1\": \"6719\",\n  \"EFX_SECSIC2\": \"6722\",\n  \"EFX_SECSICDESC1\": \"OFFICES OF HOLDING COMPANIES, NEC\",\n  \"EFX_SECSICDESC2\": \"MANAGEMENT INVESTMENT OFFICES, OPEN-END\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000016673395",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "EFX",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "EFX-100828684",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 95.56,
      "MATCH_SOURCE_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828684,\n  \"EFX_LEGAL_NAME\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO9 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828684,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828684\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO9 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"551111\",\n  \"EFX_SECNAICS2\": \"551100\",\n  \"EFX_SECNAICSDESC1\": \"Offices of Bank Holding Companies\",\n  \"EFX_SECNAICSDESC2\": \"Management of Companies and Enterprises\",\n  \"EFX_SECSIC1\": \"6719\",\n  \"EFX_SECSIC2\": \"6722\",\n  \"EFX_SECSICDESC1\": \"OFFICES OF HOLDING COMPANIES, NEC\",\n  \"EFX_SECSICDESC2\": \"MANAGEMENT INVESTMENT OFFICES, OPEN-END\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000008848967",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "CS",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "CS-GB003/0/09212382",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 58.65,
      "MATCH_SOURCE_DATA": "{\n  \"ADDRESS1\": \"EVERSHEDS HOUSE\",\n  \"ADDRESS2\": \"70 GREAT BRIDGEWATER STREET\",\n  \"ADDRESS3\": \"MANCHESTER\",\n  \"COUNTRY\": \"UK\",\n  \"CS_COMPANY_ID\": \"UK09576161\",\n  \"DATE_OF_CHANGE\": \"2016-10-11\",\n  \"NAME\": \"SUNE UK RSC HOLDCO LIMITED\",\n  \"OFFICE_TYPE\": \"1\",\n  \"ORG_NUMBER\": \"09212382\",\n  \"REG_NUMBER\": \"09212382\",\n  \"REG_TYPE\": 0,\n  \"STATUS\": \"2\",\n  \"XML_ID\": \"GB003/0/09212382\",\n  \"ZIP\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000016673392",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "EFX",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "EFX-100828667",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 95.56,
      "MATCH_SOURCE_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828667,\n  \"EFX_LEGAL_NAME\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO5 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828667,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828667\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO5 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_REGION\": \"GREATER MANCHESTER\",\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"551111\",\n  \"EFX_SECNAICS2\": \"221100\",\n  \"EFX_SECNAICSDESC1\": \"Offices of Bank Holding Companies\",\n  \"EFX_SECNAICSDESC2\": \"Electric Power Generation, Transmission and Distribution\",\n  \"EFX_SECSIC1\": \"6719\",\n  \"EFX_SECSIC2\": \"6722\",\n  \"EFX_SECSICDESC1\": \"OFFICES OF HOLDING COMPANIES, NEC\",\n  \"EFX_SECSICDESC2\": \"MANAGEMENT INVESTMENT OFFICES, OPEN-END\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000008160541",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "CS",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "CS-GB003/0/08520971",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 72.77,
      "MATCH_SOURCE_DATA": "{\n  \"ADDRESS1\": \"EVERSHEDS HOUSE\",\n  \"ADDRESS2\": \"70 GREAT BRIDGEWATER STREET\",\n  \"ADDRESS3\": \"MANCHESTER\",\n  \"COUNTRY\": \"UK\",\n  \"CS_COMPANY_ID\": \"UK08824998\",\n  \"DATE_OF_CHANGE\": \"2018-05-25\",\n  \"NAME\": \"SUNE GREEN HOLDCO LTD\",\n  \"OFFICE_TYPE\": \"1\",\n  \"ORG_NUMBER\": \"08520971\",\n  \"REG_NUMBER\": \"08520971\",\n  \"REG_TYPE\": 0,\n  \"STATUS\": \"2\",\n  \"XML_ID\": \"GB003/0/08520971\",\n  \"ZIP\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    },
    {
      "PRIMARY_MKID": "GB00000016673390",
      "MATCH_MKID": "GB00000008103038",
      "PRIMARY_MKID_SRC": "EFX",
      "MATCH_MKID_SRC": "CS",
      "PRIMARY_MKID_SOURCE_ID": "EFX-100828663",
      "MATCH_MKID_SOURCE_ID": "CS-GB003/0/08463406",
      "COUNTRYISOCODE": "GB",
      "CLUSTER_ID": 1,
      "BOOSTED_SCORE": 61.0,
      "MATCH_SOURCE_DATA": "{\n  \"ADDRESS1\": \"EVERSHEDS HOUSE\",\n  \"ADDRESS2\": \"70 GREAT BRIDGEWATER STREET\",\n  \"ADDRESS3\": \"MANCHESTER\",\n  \"COUNTRY\": \"UK\",\n  \"CS_COMPANY_ID\": \"UK08761498\",\n  \"DATE_OF_CHANGE\": \"2021-05-21\",\n  \"NAME\": \"SUNE GREENFIELD LTD\",\n  \"OFFICE_TYPE\": \"1\",\n  \"ORG_NUMBER\": \"08463406\",\n  \"REG_NUMBER\": \"08463406\",\n  \"REG_TYPE\": 0,\n  \"STATUS\": \"2\",\n  \"XML_ID\": \"GB003/0/08463406\",\n  \"ZIP\": \"M1 5ES\"\n}",
      "PRIMARY_MKID_DATA": "{\n  \"EFX_ADDRESS\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_AFFLLINKEDIND\": \"Y\",\n  \"EFX_AFFLULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_AFFLULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_AFFLULTCTRYISOCDALL\": \"USA\",\n  \"EFX_AFFLULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_AFFLULTCTRYNUMALL\": 840,\n  \"EFX_AFFLULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_AFFLULTNUMALL\": 18410363,\n  \"EFX_AFFLULTSTATEALL\": \"MO\",\n  \"EFX_AFFLULTZIP4ALL\": \"4818\",\n  \"EFX_AFFLULTZIPCODEALL\": \"63043\",\n  \"EFX_AFFULTCOUNTYALL\": \"189\",\n  \"EFX_BUSSIZE\": \"X\",\n  \"EFX_CITY\": \"MANCHESTER\",\n  \"EFX_CONTCT\": \"SHAMSUL AZHAM BIN MOHD ISA\",\n  \"EFX_CORPAMOUNT\": 2529900,\n  \"EFX_CORPAMOUNTCD\": \"K\",\n  \"EFX_CORPAMOUNTPREC\": \"MDL\",\n  \"EFX_CORPAMOUNTTP\": \"Corporate Sales\",\n  \"EFX_CORPEMPCD\": \"J\",\n  \"EFX_CORPEMPCNT\": 5000,\n  \"EFX_CTRYISOCD\": \"GBR\",\n  \"EFX_CTRYNAME\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_CTRYNUM\": 826,\n  \"EFX_CTRYTELCD\": 44,\n  \"EFX_ETHNICITY\": \"Ethnicity N/A\",\n  \"EFX_EXTRACT_DATE\": \"06/24/2024\",\n  \"EFX_FOREIGN\": \"Y\",\n  \"EFX_FSTNAM\": \"SHAMSUL AZHAM BIN MOHD\",\n  \"EFX_GENDER\": \"Gender N/A\",\n  \"EFX_ID\": 100828663,\n  \"EFX_LASTNAM\": \"ISA\",\n  \"EFX_LEGAL_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTADDRESSALL\": \"EVERSHEDS HOUSE 70 GREAT BRIDGEWATER ST\",\n  \"EFX_LEGDOMULTCITYALL\": \"MANCHESTER\",\n  \"EFX_LEGDOMULTCTRYISOCDALL\": \"GBR\",\n  \"EFX_LEGDOMULTCTRYNAMEALL\": \"United Kingdom of Great Britain and Northern Ireland\",\n  \"EFX_LEGDOMULTCTRYNUMALL\": 826,\n  \"EFX_LEGDOMULTNAMEALL\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_LEGDOMULTNUMALL\": 100828663,\n  \"EFX_LEGDOMULTZIPCODEALL\": \"M1 5ES\",\n  \"EFX_LEGLINKEDIND\": \"Y\",\n  \"EFX_LEGSUBADDRESSALL\": \"7554 WISCONSIN AVE FL 9\",\n  \"EFX_LEGSUBCITYALL\": \"BETHESDA\",\n  \"EFX_LEGSUBCOUNTYALL\": \"031\",\n  \"EFX_LEGSUBCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGSUBCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGSUBCTRYNUMALL\": 840,\n  \"EFX_LEGSUBNAMEALL\": \"SUNEDISON INTERNATIONAL, LLC\",\n  \"EFX_LEGSUBNUMALL\": 100827077,\n  \"EFX_LEGSUBSTATEALL\": \"MD\",\n  \"EFX_LEGSUBZIP4ALL\": \"3573\",\n  \"EFX_LEGSUBZIPCODEALL\": \"20814\",\n  \"EFX_LEGULTADDRESSALL\": \"13736 RIVERPORT DR STE 180\",\n  \"EFX_LEGULTCITYALL\": \"MARYLAND HEIGHTS\",\n  \"EFX_LEGULTCOUNTYALL\": \"189\",\n  \"EFX_LEGULTCTRYISOCDALL\": \"USA\",\n  \"EFX_LEGULTCTRYNAMEALL\": \"United States of America\",\n  \"EFX_LEGULTCTRYNUMALL\": 840,\n  \"EFX_LEGULTNAMEALL\": \"SUN EDISON\",\n  \"EFX_LEGULTNUMALL\": 18410363,\n  \"EFX_LEGULTSTATEALL\": \"MO\",\n  \"EFX_LEGULTZIP4ALL\": \"4818\",\n  \"EFX_LEGULTZIPCODEALL\": \"63043\",\n  \"EFX_LOCAMOUNT\": 0,\n  \"EFX_LOCEMPCNT\": 0,\n  \"EFX_MERCHANT_ID\": \"100828663\",\n  \"EFX_MRKT_TELESCORE\": 1,\n  \"EFX_MRKT_TOTALIND\": \"M\",\n  \"EFX_MRKT_TOTALSCORE\": 2,\n  \"EFX_NAME\": \"SUNE GREEN HOLDCO3 LIMITED\",\n  \"EFX_PRIMNAICSCODE\": \"551112\",\n  \"EFX_PRIMNAICSDESC\": \"Offices of Other Holding Companies\",\n  \"EFX_PRIMSIC\": \"6712\",\n  \"EFX_PRIMSICDESC\": \"OFFICES OF BANK HOLDING COMPANIES\",\n  \"EFX_PROJECT_ID\": 0,\n  \"EFX_SECCTRYNUM\": 0,\n  \"EFX_SECNAICS1\": \"221112\",\n  \"EFX_SECNAICS2\": \"221113\",\n  \"EFX_SECNAICS3\": \"221114\",\n  \"EFX_SECNAICS4\": \"221115\",\n  \"EFX_SECNAICSDESC1\": \"Fossil Fuel Electric Power Generation\",\n  \"EFX_SECNAICSDESC2\": \"Nuclear Electric Power Generation\",\n  \"EFX_SECNAICSDESC3\": \"Solar Electric Power Generation\",\n  \"EFX_SECNAICSDESC4\": \"Wind Electric Power Generation\",\n  \"EFX_SECSIC1\": \"4911\",\n  \"EFX_SECSICDESC1\": \"ELECTRIC SERVICES\",\n  \"EFX_TITLECD\": \"3 \",\n  \"EFX_TITLEDESC\": \"Manager\",\n  \"EFX_YREST\": \"2014\",\n  \"EFX_ZIPCODE\": \"M1 5ES\"\n}",
      "IS_LOCKED": true,
      "LOCKED_BY": null
    }
  ]


  // Toggle function for expanding/collapsing item details
  const toggleExpand = async (uniqueKey, item) => {
    console.log(item, '=***********')
    try {
      const newdata = data.map((v) => {
        const MATCH_SOURCE_DATA = JSON.parse(v.MATCH_SOURCE_DATA);
        const PRIMARY_MKID_DATA = JSON.parse(v.PRIMARY_MKID_DATA);

        MATCH_SOURCE_DATA.fullAddress = v.MATCH_MKID_SRC === 'CS'
          ? `${MATCH_SOURCE_DATA.NAME}\n${MATCH_SOURCE_DATA.ADDRESS1} ${MATCH_SOURCE_DATA.ADDRESS2}\n${MATCH_SOURCE_DATA.ADDRESS3}\n${MATCH_SOURCE_DATA.ZIP}\n${MATCH_SOURCE_DATA.COUNTRY}`
          : `${MATCH_SOURCE_DATA.EFX_ADDRESS}\n${MATCH_SOURCE_DATA.EFX_CITY}\n${MATCH_SOURCE_DATA.EFX_ZIPCODE}\n${MATCH_SOURCE_DATA.EFX_CTRYNAME}`;

        console.log(MATCH_SOURCE_DATA.fullAddress, '---------------');

        return { ...v, MATCH_SOURCE_DATA, PRIMARY_MKID_DATA };
      });

      setGetDataMKID(newdata);
    } catch (error) {
      console.error("Error fetching world regions:", error);
    }
    setExpandedId((prev) => {
      const isCollapsing = prev === uniqueKey;
      return isCollapsing ? null : uniqueKey;
    });
  };

  useEffect(() => {

    if (selectedId !== null) {
      console.log(selectedId, 'index')
      const index = getDataMKID.findIndex((v) => v.MATCH_MKID === selectedId);
      const str = onNextPre.split('-')[0];
      if (index !== -1) {
        let nextIndex;
        if (str === "Next") {
          nextIndex = (index + 1) % getDataMKID.length; // Wrap around using modulo for "next"
        } else if (str === "Pre") {
          nextIndex = (index - 1 + getDataMKID.length) % getDataMKID.length; // Wrap around using modulo for "previous"
        }
        const updatedData = getDataMKID[nextIndex];
        setSelectedId(updatedData.MATCH_MKID);
        onSelectData(updatedData);
      }
    }
  }, [onNextPre]);

  // Handle item selection for data display
  const handleSelectData = (id, item) => {
    if (selectedId === id) {
      setSelectedId(null);
      onSelectData(null);
    } else {
      setSelectedId(id);
      onSelectData(id && item ? item : null);
    }
  };

  // Infinite scrolling functionality to load more items
  const handleScroll = () => {
    const scrollContainer = document.querySelector('.scroll-container');
    // Check if user has reached the bottom of the scroll container
    if (scrollContainer.scrollTop + scrollContainer.clientHeight >= scrollContainer.scrollHeight) {
      setDisplayedCount((prevCount) => prevCount + 10); // Load 10 more records
    }
  };

  // Attach and clean up the scroll event listener
  useEffect(() => {
    const scrollContainer = document.querySelector('.scroll-container');
    if (scrollContainer) {
      scrollContainer.addEventListener('scroll', handleScroll);
    }
    return () => {
      if (scrollContainer) {
        scrollContainer.removeEventListener('scroll', handleScroll);
      }
    };
  }, []);

  return (
    <div className="bg-[#F9FAFB] rounded-3xl h-[79%] w-[42%] py-4 pb-3 px-4 overflow-y-auto scroll-container">

      {/* Header section displaying the column titles */}
      <div className="flex items-center gap-7 text-sm">
        <div className="w-1/2 flex items-center">
          <p className="w-1/2 text-center pl-4">Markaaz ID</p>
          <p className="w-1/2 text-right">Source Record ID</p>
        </div>
        <div className="w-1/2 flex items-center">
          <p className="w-1/2 text-left">Company</p>
          <p className="w-1/2 text-left">Matches</p>
        </div>
        <div>
          <p className="text-xs">Total Records: {totalRecords}</p>
        </div>
      </div>

      {/* Map through the stewardship data to display each record */}
      {stewardshipData.slice(0, displayedCount).map((item, index) => {


        const uniqueKey = `${item.MK_ID}-${index}`;

        return (
          <div key={uniqueKey} className="bg-white rounded-2xl p-3 my-2">
            {/* Display record details */}
            <div className="text-[#66668F] flex text-xs justify-between px-1">
              <div className="w-1/2 pr-3 pl-1 gap-2 flex justify-between">
                {/* Toggle expand icon */}
                {expandedId === uniqueKey ? (
                  <IoRemoveOutline
                    onClick={() => toggleExpand(uniqueKey, item)}
                    className="bg-[#e6f1fa] text-[#0A78CD] rounded-full shrink-0 p-1 text-3xl cursor-pointer"
                  />
                ) : (
                  <IoAddOutline
                    onClick={() => toggleExpand(uniqueKey, item)}
                    className="bg-[#e6f1fa] text-[#0A78CD] rounded-full shrink-0 p-1 text-3xl cursor-pointer"
                  />
                )}
                <div className="flex w-full font-light gap-5 justify-between">
                  <div className="w-1/2">
                    <p>{item.MK_ID}</p>
                    <p>{item.SOURCE}</p>
                  </div>
                  <p className="w-1/2 text-left">{item.SOURCE}</p>
                </div>
              </div>
              <div className="w-1/2 pr-3 pl-1 gap-2 flex justify-between">
                <div className="flex w-full font-light gap-5 justify-between">
                  <div className="w-1/2 flex flex-col gap-2">
                    <p>{item.COMPANY_NAME}</p>
                    <div className="flex gap-1">
                      <SlLocationPin className="shrink-0 text-base text-[#0A78CD] font-semibold" />
                      {item.FULL_ADDRESS}
                    </div>
                  </div>
                  <div className="w-1/2 text-left h-full flex flex-col pb-3 justify-between">
                    <p>Matches 1 Of {item.MATCH_COUNT}</p>
                    <button className="rounded-full w-fit py-2 px-4 bg-[#0A78CD] box-shadow text-white font-medium">
                      Reject
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Expanded view section */}
            {expandedId === uniqueKey && getDataMKID.map((item) => (
              <div className="bg-[#ECF5FB] rounded-xl mt-2 overflow-hidden">
                <div className="bg-[#C8D3DB] p-3">
                  <div className="flex items-center w-full justify-between px-2">
                    <div className="w-1/2 flex items-center text-sm">
                      <p className="w-1/2">Markaaz ID</p>
                      <p className="w-1/2">Source Record ID</p>
                    </div>
                    <div className="w-1/2 flex items-center text-sm">
                      <p className="w-1/2">Company</p>
                      <p className="w-1/2">Match(%)</p>
                    </div>
                  </div>
                </div>

                {/* Expanded item details */}
                <div className="p-3 border-b border-[#66668F33]">
                  <div className="flex w-full font-light text-[#66668F] justify-between px-2">
                    <div className="w-1/2 flex text-xs">
                      <div className="w-1/2">
                        <p>{item.PRIMARY_MKID}</p>
                        <p>{item.PRIMARY_MKID_SOURCE_ID}</p>
                      </div>
                      <p className="w-1/2">{item.MATCH_MKID_SOURCE_ID}</p>
                    </div>
                    <div className="w-1/2 flex text-xs">
                      <div className="w-1/2 flex flex-col gap-2">
                        <p>{item.MATCH_MKID_SRC === 'CS' ? item.MATCH_SOURCE_DATA.NAME : item.MATCH_SOURCE_DATA.EFX_AFFLULTNAMEALL}</p>
                        <div className="flex gap-1">
                          <SlLocationPin className="shrink-0 text-base text-[#0A78CD] font-semibold" />
                          <p>{item.MATCH_SOURCE_DATA.fullAddress}</p>
                        </div>
                      </div>
                      <div className="w-1/2 flex flex-col justify-between gap-2 pb-4">
                        <div className="flex w-full items-center justify-between pb-3">
                          <p>{item.BOOSTED_SCORE}</p>
                          {/* Select/Unselect Button */}
                          {selectedId === item.MATCH_MKID ? (
                            <IoChevronBackOutline
                              onClick={() => handleSelectData(item.MATCH_MKID, item)}
                              className="bg-[#0A78CD] text-white p-1 rounded-full shrink-0 text-3xl cursor-pointer"
                            />
                          ) : (
                            <IoChevronForwardOutline
                              onClick={() => handleSelectData(item.MATCH_MKID, item)}
                              className="bg-[#f0f0f4] text-[#66668F] p-1 rounded-full shrink-0 text-3xl cursor-pointer"
                            />
                          )}
                        </div>
                        <ExpandedItemsButton item={item}/>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        );
      })}
    </div>
  );
};

export default StewardshipLeft;
